### ISSUE TITLE
cookies are not being sent in xhr request

### ISSUE THREAD

**Issue by erikyuzwa** [hstove/electron-cookies#6]
Hey,
I'm not sure which project this issue belongs, but I'm not seeing the `document.cookie` value being sent along with the XHR request header.

I'm using Angular within the Electron shell so I'm using the `withCredentials = true` approach, similar to using `withCredentials: true` via `$.ajax` request.

when I include the `electron-cookies` package, an `alert(document.cookie)` gives me the proper cookies that need to be included in the XHR request.

Hopefully that's not too vague. Any ideas? thanks!

**Comment by hstove** [comment]
Hm, unfortunately I don't think this is the right repository for this, as it seems like something to do with electron's implementation of XHR requests. You might want to try manually setting a `Set-Cookie` header  to see if that works.

Thanks for reaching out!

**Comment by erikyuzwa** [comment]
thanks @hstove - I kinda figured as much. Will do, I'll try looking into the main electron project for help there. :+1:
